let songs = [
  {
    name: "Gurenge",
    path: "gurenge",
    artist: "LISA",
    cover: "img/kv.webp",
  },

  {
    name: "Hey Kids!",
    path: "noragammi",
    artist: "Kyouran",
    cover: "img/noragami.jpg",
  },
  {
    name: "Hacking to the gate",
    path: "gate",
    artist: "Steins:Gate OP",
    cover: "img/gate.jpg",
  },
  {
    name: "Kawaki No Ameku",
    path: "kawameku",
    artist: "Minami",
    cover: "img/Kawameku.webp",
  },
  // {
  //   name: "Neon Blade",
  //   path: "neonBlade",
  //   artist: "Moondeity ",
  //   cover: "img/neonBlade.webp",
  // },
  {
    name: "Zettai Zetsumei",
    path: "tpn",
    artist: "The Promised Neverland ending",
    cover: "img/tpn.jpg",
  },
  {
    name: "Blue Bird",
    path: "blueBird",
    artist: "Ikimonogakari ",
    cover: "img/blueBird.jpg",
  },
  {
    name: "VORACITY",
    path: "overlord",
    artist: "MYTH & ROID",
    cover: "img/overlord.jpg",
  },
  {
    name: "The Rumbling",
    path: "atackontition",
    artist: "SIM",
    cover: "img/atackontitan.jpg",
  },
  {
    name: "Tokyo Ghoul",
    path: "ghoul",
    artist: "Opening 3",
    cover: "img/ghoul.png",
  },
  {
    name: "Zankyosanka",
    path: "zankyosanka",
    artist: "Aimer",
    cover: "img/zanko.webp",
  },
  {
    name: "Toradora",
    path: "dora",
    artist: "Opening 1",
    cover: "img/dora.jpg",
  },
  {
    name: "Love is War",
    path: "kag",
    artist: "Kaguya sama 1 OP",
    cover: "img/love.jpeg",
  },
  {
    name: "This Game",
    path: "nogamenolife",
    artist: "Konomi Suzuki",
    cover: "img/No_Game_No_Life.webp",
  },
  {
    name: "Black Catcher",
    path: "vicke",
    artist: "Vickeblanka",
    cover: "img/blackcatch.webp",
  },
  {
    name: "The Day",
    path: "bnha",
    artist: "BNHA 1 OP ",
    cover: "img/bnha.png",
  },
  {
    name: "Re:Re",
    path: "rased",
    artist: "Erased Opening",
    cover: "img/rased.jpg",
  },
  {
    name: "Spy X Family",
    path: "spyxfamliy",
    artist: "Ending | Outro",
    cover: "img/ania.jpg",
  },
  // {
  //   name: "The Imperial March",
  //   path: "strtwars",
  //   artist: "Star Wars",
  //   cover: "img/weider.jpg",
  // },
  {
    name: "99.9",
    path: "mob",
    artist: "MOB CHOIR",
    cover: "img/mob.webp",
  },
  {
    name: "Vinland Saga",
    path: "vinland",
    artist: "Opening",
    cover: "img/vinland.JPG",
  },
  {
    name: "Netsujo No Spectrum",
    path: "sevendeadlysins1",
    artist: "Ikimonogakari",
    cover: "img/sds.jpg",
  },
  {
    name: "Like Flames",
    path: "likeFlames",
    artist: "MindaRyn",
    cover: "img/likeFlame.jpg",
  },
  {
    name: "Cowboy Bebop",
    path: "cowboybebop",
    artist: "Opening 1",
    cover: "img/cowboybebop.jpg",
  },
  {
    name: "One Piece",
    path: "onepiece",
    artist: "Opening 1",
    cover: "img/op.jpg",
  },
  {
    name: "RISE",
    path: "shield",
    artist: "MADKID",
    cover: "img/shield.jpg",
  },
  {
    name: "Perfect Time",
    path: "sdsost",
    artist: "Hiroyuki Sawano",
    cover: "img/sds.jpg",
  },
  {
    name: "Bleach",
    path: "bleach13",
    artist: "13 Opening",
    cover: "img/Bleach.jpg",
  },
  {
    name: "Death Parade",
    path: "deathparade",
    artist: "Opening",
    cover: "img/dop.jpg",
  },
  {
    name: "THE HERO !!",
    path: "opm",
    artist: "JAM PROJECT",
    cover: "img/opm.jpg",
  },
  {
    name: "Merry Go Round",
    path: "merrygoround",
    artist: "Joe Hisashi",
    cover: "img/hmc.jpg",
  },
  {
    name: "Crossing Field",
    path: "sao1",
    artist: "LISA",
    cover: "img/sao1.webp",
  },
  {
    name: "Ignite",
    path: "sao3",
    artist: "Eir Aoi",
    cover: "img/sao2.png",
  },
  {
    name: "ADAMAS",
    path: "adamas",
    artist: "LISA",
    cover: "img/saoal.webp",
  },
  {
    name: "Gurren Lagann",
    path: "gl",
    artist: "Opening",
    cover: "img/gl.jpg",
  },
  // {
  //   name: "Bon Bon Chocolate",
  //   path: "bbc",
  //   artist: "EVERGLOW",
  //   cover: "img/everglowbn.jpg",
  // },
  // {
  //   name: "WANNABE",
  //   path: "wannabe",
  //   artist: "ITZY",
  //   cover: "img/itzywnbe.jpg",
  // },
  {
    name: "Шоколад",
    path: "chocol",
    artist: "Madi & Bonapart",
    cover: "img/jigi.png",
  },
  {
    name: "24/7",
    path: "face247",
    artist: "FACE",
    cover: "img/jigi.png",
  },
  {
    name: "Наивная",
    path: "наивная",
    artist: "M'Dee, abdr. & The Limba",
    cover: "img/jigi.png",
  },
  {
    name: "Девочка в тренде",
    path: "miko",
    artist: "Miko",
    cover: "img/jigi.png",
  },
  {
    name: "Оп-оңай",
    path: "oponai",
    artist: "Duman",
    cover: "img/jigi.png",
  },
  {
    name: "СИНИЕ ФИАЛКИ",
    path: "siniefialki",
    artist: "The Limba",
    cover: "img/jigi.png",
  },
  {
    name: "Uide",
    path: "uide",
    artist: "Darkhan juzz",
    cover: "img/jigi.png",
  },
  {
    name: "Влюбился в нее",
    path: "vlyubilsyavnee",
    artist: "Deesmi",
    cover: "img/jigi.png",
  },
  {
    name: "ЮМОРИСТ",
    path: "yumorist",
    artist: "FACE",
    cover: "img/jigi.png",
  },
  {
    name: "Влюбился",
    path: "adresovvlubilsya",
    artist: "The Adresov",
    cover: "img/jigi.png",
  },
  {
    name: "Алмата-Семей",
    path: "almatysemey",
    artist: "Bonapart",
    cover: "img/jigi.png",
  },
  {
    name: "Alystama",
    path: "alystama",
    artist: "Moldanazar",
    cover: "img/jigi.png",
  },
  {
    name: "Антигерой",
    path: "antigeroy",
    artist: "ELMAN",
    cover: "img/jigi.png",
  },
  {
    name: "Beinen",
    path: "beinen",
    artist: "Madeniyett",
    cover: "img/jigi.png",
  },
  {
    name: "Богатыми",
    path: "bogatymi",
    artist: "Фогель",
    cover: "img/jigi.png",
  },
  {
    name: "Карусель",
    path: "carousel",
    artist: "V $ X V PRINCE",
    cover: "img/jigi.png",
  },
  {
    name: "Цветы",
    path: "cvety",
    artist: "V $ X V PRINCE",
    cover: "img/jigi.png",
  },
  {
    name: "Детство",
    path: "detstvo",
    artist: "Rauf & Faik",
    cover: "img/jigi.png",
  },
  {
    name: "Досым",
    path: "dosym",
    artist: "Raim",
    cover: "img/jigi.png",
  },
  {
    name: "Дуракам везет",
    path: "durakamvezet",
    artist: "Фогель",
    cover: "img/jigi.png",
  },
  {
    name: "Это ли счастье",
    path: "etolischaste",
    artist: "Rauf & Faik",
    cover: "img/jigi.png",
  },
  {
    name: "Я люблю тебя",
    path: "ialublyu",
    artist: "Rauf & Faik",
    cover: "img/jigi.png",
  },
  {
    name: "Май",
    path: "jamikmay",
    artist: "Jamik",
    cover: "img/jigi.png",
  },
  {
    name: "Какая ты красивая",
    path: "kakayati",
    artist: "Akha",
    cover: "img/jigi.png",
  },
  {
    name: "Кино",
    path: "kino",
    artist: "MACAN",
    cover: "img/jigi.png",
  },
  {
    name: "Космос",
    path: "kosmos",
    artist: "Скриптонит",
    cover: "img/jigi.png",
  },
  {
    name: "Вечера",
    path: "vechera",
    artist: "Rauf & Faik",
    cover: "img/jigi.png",
  },
  {
    name: "Запомни I love you",
    path: "zapomniiloveyou",
    artist: "Rauf & Faik и SHAMI",
    cover: "img/jigi.png",
  },
  {
    name: "Много тебя",
    path: "mnogotebya",
    artist: "M'Dee",
    cover: "img/jigi.png",
  },
  {
    name: "На лету",
    path: "naletu",
    artist: "V $ X V PRINCE",
    cover: "img/jigi.png",
  },
  {
    name: "Әндетемін",
    path: "ndetemin",
    artist: "Мирас Жугунусов",
    cover: "img/jigi.png",
  },
  {
    name: "По уши в тебя влюблен",
    path: "poushi",
    artist: "Myagi",
    cover: "img/jigi.png",
  },
  {
    name: "Refresh",
    path: "refresh",
    artist: "All kazakhs best",
    cover: "img/jigi.png",
  },
  {
    name: "Салют Вера",
    path: "salyutvera",
    artist: "Mona songz",
    cover: "img/jigi.png",
  },
  {
    name: "Шекер",
    path: "sheker",
    artist: "Darkhan Juzz",
    cover: "img/jigi.png",
  },
  {
    name: "Поцелованная солнцем",
    path: "solnce",
    artist: "Mona Songz, Shvringvn",
    cover: "img/jigi.png",
  },
  {
    name: "Танец",
    path: "tanec",
    artist: "ottenok",
    cover: "img/jigi.png",
  },
  {
    name: "Oralma qashqyn",
    path: "taspayoralmaqashqyn",
    artist: "Taspay",
    cover: "img/jigi.png",
  },
  {
    name: "Точка или запятая",
    path: "tochkaz",
    artist: "V $ X V PRINCE",
    cover: "img/jigi.png",
  },
  {
    name: "Все, что дал мне этот вечер",
    path: "vsechtodalmne",
    artist: "Introvert",
    cover: "img/jigi.png",
  },
  {
    name: "Выдох-вдох",
    path: "vydohvdoh",
    artist: "M'Dee",
    cover: "img/jigi.png",
  },
  {
    name: "ВЫПУСКНИК",
    path: "vypuskink",
    artist: "ФОГЕЛЬ",
    cover: "img/jigi.png",
  },
  {
    name: "Взять взять",
    path: "vzyat",
    artist: "Cali",
    cover: "img/jigi.png",
  },
  {
    name: "Я в моменте",
    path: "yavmomente",
    artist: "Джарахов, Markul",
    cover: "img/jigi.png",
  },
  {
    name: "Юность",
    path: "yunost",
    artist: "Dabro",
    cover: "img/jigi.png",
  },
  {
    name: "Зымыран",
    path: "zymyran",
    artist: "Мирас Жугунусов",
    cover: "img/jigi.png",
  },
  {
    name: "24HRS",
    path: "itzy24h",
    artist: "ITZY",
    cover: "img/itzywnbe.jpg",
  },
  {
    name: "365",
    path: "itzy365",
    artist: "ITZY",
    cover: "img/chm.jpg",
  },

  {
    name: "I don't wanna dance",
    path: "itzyidwn",
    artist: "ITZY",
    cover: "img/itzywnbe.jpg",
  },
  {
    name: "ICY",
    path: "icy",
    artist: "ITZY",
    cover: "img/itzyic.webp",
  },
  {
    name: "KIDDING ME",
    path: "kidme",
    artist: "ITZY",
    cover: "img/mafia.jpg",
  },
  {
    name: "MIDZY",
    path: "midzy",
    artist: "ITZY",
    cover: "img/midzy.jpg",
  },
  {
    name: "Nobody like you",
    path: "nobodylike",
    artist: "ITZY",
    cover: "img/itzywnbe.jpg",
  },
  {
    name: "RACE",
    path: "race",
    artist: "ITZY",
    cover: "img/chm.jpg",
  },
  {
    name: "Sorry not Sorry",
    path: "sns",
    artist: "ITZY",
    cover: "img/mafia.jpg",
  },
  {
    name: "THAT'S A NO NO",
    path: "that",
    artist: "ITZY",
    cover: "img/itzywnbe.jpg",
  },
  {
    name: "TING TING TING",
    path: "ting",
    artist: "ITZY",
    cover: "img/itzywnbe.jpg",
  },
  {
    name: "IN THE MORNING",
    path: "morning",
    artist: "ITZY",
    cover: "img/mafia.jpg",
  },
  {
    name: "SHOOT",
    path: "shoot",
    artist: "ITZY",
    cover: "img/mafia.jpg",
  },
  {
    name: "TENNIS 0:0",
    path: "tennis",
    artist: "ITZY",
    cover: "img/mafia.jpg",
  },
  {
    name: "Love to hate",
    path: "luvhate",
    artist: "BLACKPINK",
    cover: "img/bp.jpg",
  },
  {
    name: "Pretty Savage",
    path: "prettysav",
    artist: "BLACKPINK",
    cover: "img/bp.jpg",
  },
  {
    name: "DALLA DALLA",
    path: "dalladalla",
    artist: "ITZY",
    cover: "img/dl.webp",
  },
  {
    name: "Forever Young",
    path: "fory",
    artist: "BLACKPINK",
    cover: "img/fy.webp",
  },
  {
    name: "FIESTA",
    path: "fiesta",
    artist: "IZ*ONE",
    cover: "img/iz.jpg",
  },
  {
    name: "AYAYAYA",
    path: "ayaya",
    artist: "IZ*ONE",
    cover: "img/iz.jpg",
  },
  {
    name: "CHEERS",
    path: "cheers",
    artist: "SEVENTEEN  ",
    cover: "img/cheer.png",
  },
  {
    name: "DDU-DU DDU-DU",
    path: "ddudu",
    artist: "BLACKPINK",
    cover: "img/fy.webp",
  },
  {
    name: "Moon",
    path: "moon",
    artist: "EVERGLOW",
    cover: "img/everglowbn.jpg",
  },
  {
    name: "Pirate",
    path: "pirate",
    artist: "EVERGLOW",
    cover: "img/pirate.jpg",
  },
  {
    name: "Hush",
    path: "hush",
    artist: "EVERGLOW",
    cover: "img/hush.jpg",
  },
  {
    name: "FIRST",
    path: "first",
    artist: "EVERGLOW",
    cover: "img/first.jpg",
  },
  {
    name: "Dun dun",
    path: "dun",
    artist: "EVERGLOW",
    cover: "img/dn.jpg",
  },
  {
    name: "Adios",
    path: "adi",
    artist: "EVERGLOW",
    cover: "img/hush.jpg",
  },
];
